services:

  postgres:
    image: postgres:16-alpine
    container_name: once-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=once
      - POSTGRES_PASSWORD=once_password_123
      - POSTGRES_DB=once
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: once-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage

  neo4j:
    image: neo4j:latest
    container_name: once-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/once_password_123
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
